"use strict";
const bcrypt = require("bcryptjs");
module.exports = {
  up: async (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert(
      "users",
      [
        {
          id: 1,
          companyId: 1,
          roleId: 1,
          email: "shoaib@pcec.com.pk",
          firstName: "Shoaib Mustafa",
          lastName: "Siddique",
          password: bcrypt.hashSync("PEC1234!", 8),
          department:'Project Management',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 2,
          companyId: 1,
          roleId: 2,
          email: "mzubair@pcec.com.pk",
          firstName: "Muhammad Zubair",
          lastName: "Khan",
          password: bcrypt.hashSync("PEC123!", 8),
          department:'Mechanical',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 3,
          companyId: 1,
          roleId: 3,
          email: "farrukh@pcec.com.pk",
          firstName: "Syed Farrukh",
          lastName: "Rehman",
          password: bcrypt.hashSync("PEC123!", 8),
          department:'Civil/Structure',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 4,
          companyId: 1,
          roleId: 2,
          email: "rabia@pcec.com.pk",
          firstName: "Syeda Rabia",
          lastName: "Shahid",
          password: bcrypt.hashSync("PEC123!", 8),
          department:'Civil/Structure',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 5,
          companyId: 1,
          roleId: 2,
          email: "bisma.naeem@pcec.com.pk",
          firstName: "Bisma",
          lastName: "Naeem",
          password: bcrypt.hashSync("PEC123!", 8),
          department:'Electrical',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 6,
          companyId: 1,
          roleId: 2,
          email: "yasra@pcec.com.pk",
          firstName: "Yasra",
          lastName: "Aslam",
          password: bcrypt.hashSync("PEC123!", 8),
          department:'Process',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 7,
          companyId: 1,
          roleId: 3,
          email: "daniyal@pcec.com.pk",
          firstName: "Muhammad",
          lastName: "Daniyal",
          password: bcrypt.hashSync("PEC123!", 8),
          department:'Mechanical',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 8,
          companyId: 1,
          roleId:4,
          email: "m.hassan@pcec.com.pk",
          firstName: "Muhammad Hassan",
          lastName: "Raza",
          password: bcrypt.hashSync("PEC123!", 8),
          department:'Mechanical',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 9,
          companyId: 1,
          roleId:3,
          email: "nabeel@pcec.com.pk",
          firstName: "Nabeel Rehman",
          lastName: "Hashmi",
          password: bcrypt.hashSync("PEC123!", 8),
          department:'Mechanical',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10,
          companyId: 1,
          roleId:4,
          email: "yumn@pcec.com.pk",
          firstName: "Yumn",
          lastName: "Iqbal",
          password: bcrypt.hashSync("PEC123!", 8),
          department:'Process',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 11,
          companyId: 1,
          roleId:4,
          email: "razia@pcec.com.pk",
          firstName: "Razia",
          lastName: "Jamil",
          password: bcrypt.hashSync("PEC123!", 8),
          department:'Process',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 12,
          companyId: 1,
          roleId:5,
          email: "s.qamar@pcec.com.pk",
          firstName: "Syed Qamar",
          lastName: "Ali",
          password: bcrypt.hashSync("PEC123!", 8),
          department:'Piping',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 13,
          companyId: 1,
          roleId:5,
          email: "s.hamza@pcec.com.pk",
          firstName: "Syed",
          lastName: "Hamza",
          password: bcrypt.hashSync("PEC123!", 8),
          department:'Piping',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 14,
          companyId: 1,
          roleId:5,
          email: "maaz@pcec.com.pk",
          firstName: "Maaz",
          lastName: "Farrukh",
          password: bcrypt.hashSync("PEC123!", 8),
          department:'Piping',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 15,
          companyId: 1,
          roleId:4,
          email: "m.ali@pcec.com.pk",
          firstName: "Muhammad Ali",
          lastName: "Khan",
          password: bcrypt.hashSync("PEC123!", 8),
          department:'Civil',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 16,
          companyId: 1,
          roleId:5,
          email: "mustaqeem@pcec.com.pk",
          firstName: "Muhammad",
          lastName: "Mustaqeem",
          password: bcrypt.hashSync("PEC123!", 8),
          department:'Civil',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 17,
          companyId: 1,
          roleId:4,
          email: "m.hamza@pcec.com.pk",
          firstName: "Muhammad",
          lastName: "Hamza",
          password: bcrypt.hashSync("PEC123!", 8),
          department:'Civil',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 18,
          companyId: 1,
          roleId:5,
          email: "ayan@pcec.com.pk",
          firstName: "Ayan",
          lastName: "Khan",
          password: bcrypt.hashSync("PEC123!", 8),
          department:'Piping',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 19,
          companyId: 1,
          roleId:5,
          email: "m.waqas@pcec.com.pk",
          firstName: "Muhammad Waqas Ali",
          lastName: "Khan",
          password: bcrypt.hashSync("PEC123!", 8),
          department:'Piping',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 20,
          companyId: 1,
          roleId:5,
          email: "s.waris@pcec.com.pk",
          firstName: "Syed Waris",
          lastName: "Hassan",
          password: bcrypt.hashSync("PEC123!", 8),
          department:'Piping',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 21,
          companyId: 1,
          roleId:5,
          email: "akif@pcec.com.pk",
          firstName: "Akif",
          lastName: "Shoaib",
          password: bcrypt.hashSync("PEC123!", 8),
          department:'Piping',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 22,
          companyId: 1,
          roleId:5,
          email: "m.hammad@pcec.com.pk",
          firstName: "Muhammad Hammad",
          lastName: "Khan",
          password: bcrypt.hashSync("PEC123!", 8),
          department:'Piping',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 23,
          companyId: 1,
          roleId:3,
          email: "sm.ammar@pcec.com.pk",
          firstName: "Syed Muhammad",
          lastName: "Ammar",
          password: bcrypt.hashSync("PEC123!", 8),
          department:'Mechanical',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 24,
          companyId: 1,
          roleId:3,
          email: "rayyan@pcec.com.pk",
          firstName: "Muhammad",
          lastName: "Rayyan",
          password: bcrypt.hashSync("PEC123!", 8),
          department:'Electrical',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 25,
          companyId: 1,
          roleId:5,
          email: "raza@pcec.com.pk",
          firstName: "Ahmad",
          lastName: "Raza",
          password: bcrypt.hashSync("PEC123!", 8),
          department:'Instrumentation',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 26,
          companyId: 1,
          roleId:4,
          email: "arooba@pcec.com.pk",
          firstName: "Hafiza Arooba",
          lastName: "Fatima",
          password: bcrypt.hashSync("PEC123!", 8),
          department:'Electrical',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 27,
          companyId: 1,
          roleId:5,
          email: "shahid@pcec.com.pk",
          firstName: "Muhammad",
          lastName: "Shahid",
          password: bcrypt.hashSync("PEC123!", 8),
          department:'Piping',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 28,
          companyId: 1,
          roleId:5,
          email: "taimoor@pcec.com.pk",
          firstName: "Syed Taimoor",
          lastName: "Iqbal",
          password: bcrypt.hashSync("PEC123!", 8),
          department:'Piping',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 29,
          companyId: 1,
          roleId:3,
          email: "hafeez@pcec.com.pk",
          firstName: "Abdul",
          lastName: "Hafeez",
          password: bcrypt.hashSync("PEC123!", 8),
          department:'Civil/Structure',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 30,
          companyId: 1,
          roleId:4,
          email: "roshan@pcec.com.pk",
          firstName: "Muhammad",
          lastName: "Roshan",
          password: bcrypt.hashSync("PEC123!", 8),
          department:'Mechanical',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 31,
          companyId: 1,
          roleId:3,
          email: "ayesha@pcec.com.pk",
          firstName: "Ayesha",
          lastName: "Farooq",
          password: bcrypt.hashSync("PEC123!", 8),
          department:'Electrical',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 32,
          companyId: 1,
          roleId:4,
          email: "mustafa@pcec.com.pk",
          firstName: "Mustafa",
          lastName: "Khan",
          password: bcrypt.hashSync("PEC123!", 8),
          department:'Mechanical',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 33,
          companyId: 1,
          roleId:4,
          email: "ahsan@pcec.com.pk",
          firstName: "Ahsan",
          lastName: "Samdani",
          password: bcrypt.hashSync("PEC123!", 8),
          department:'Electrical',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 34,
          companyId: 1,
          roleId:5,
          email: "waleed@pcec.com.pk",
          firstName: "Waleed",
          lastName: "Ahmad",
          password: bcrypt.hashSync("PEC123!", 8),
          department:'Piping',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 35,
          companyId: 1,
          roleId:5,
          email: "anas@pcec.com.pk",
          firstName: "Anas",
          lastName: "Hamid",
          password: bcrypt.hashSync("PEC123!", 8),
          department:'Piping',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 36,
          companyId: 1,
          roleId:4,
          email: "ovais@pcec.com.pk",
          firstName: "Muhammad",
          lastName: "Ovais",
          password: bcrypt.hashSync("PEC123!", 8),
          department:'Civil',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      { ignoreDuplicates: true }
    );
  },

  down: async (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete("users", null, {});
  },
};